dovecot/documentation

source/configuration_manual/namespace/index.rst
=> configuration_manual/namespace: support \Important special-use flag

source/admin_manual/list_of_events.rst, source/configuration_manual/stats/index.rst
=> list_of_events: Update push notifcation event

source/configuration_manual/mail_location/obox/amazon_s3.rst, source/configuration_manual/mail_location/obox/http_based_object_storages.rst, source/configuration_manual/mail_location/obox/other_s3-compatible_storages.rst
Introduce the aws-s3 scheme and add more structure.
=> configuration_manual: Update aws-s3 and other s3-compatible storages

source/configuration_manual/authentication/oauth2.rst
=> oauth2: Document local validation support

source/configuration_manual/authentication/oauth2.rst, source/configuration_manual/service_configuration.rst
In addition fix smaller typos/indentation errors.
=> configuration_manual: update oauth2  full config

source/admin_manual/known_issues/large_cache.rst, source/admin_manual/troubleshooting.rst, source/settings/dovecot_core_settings.rst
=> Document large dovecot.index.cache issues

source/admin_manual/known_issues/large_cache.rst, source/settings/dovecot_core_settings.rst
Slight fixups to large cache issue documentation.
=> Large cache changes

source/configuration_manual/zlib_plugin.rst
=> zlib_plugin.rst: Document zstd

source/admin_manual/namespaces.rst
=> admin_manual/namespaces: Update folder name documentation

source/configuration_manual/coi.rst
=> configuration_manual/coi/webpush: Add link to webpush spec

source/admin_manual/list_of_events.rst
=> list_of_events: imap-commands - Add cmd_input_name and update cmd_name

source/configuration_manual/mail_location/obox/amazon_s3.rst
Some improvements based on DOT teams feedback.
=> More aws-s3 updates

source/configuration_manual/mail_cache_settings.rst, source/settings/core.rst
=> mail_cache_settings, settings/core: Update mail cache settings

source/admin_manual/list_of_events.rst
=> list_of_events.rst: Document new dict events

source/configuration_manual/index.rst, source/configuration_manual/stats/index.rst, source/configuration_manual/stats/openmetrics.rst
JIRA: DOV-3931
Documentation for the new openmetrics exporter.
=> stats: Document OpenMetrics

source/admin_manual/login_proxy.rst
For now just document the states.
=> admin_manual: Add login_proxy

source/configuration_manual/authentication/oauth2.rst
=> oauth2: Document changes to oauth2 local validation

requirements.txt, source/admin_manual/cassandra/cassandra.rst, source/admin_manual/cassandra/cassandra.yaml.rst, source/admin_manual/lua.rst
- upgrade to 3.0.4
- fix random things
=> Small fixes

source/configuration_manual/authentication/oauth2.rst
=> oauth2: Update documentation

source/admin_manual/lua.rst
Broken in fd3da22b260725429f497f05d380672bb85f7f7c
=> lua: Fix syntax to make things actually visible

source/configuration_manual/dovemon.rst
=> configuration_manual/dovemon: Include brief explanations for poll_* checks

source/settings/core.rst
=> settings: Add login_proxy_timeout and login_proxy_max_reconnects

source/admin_manual/list_of_events.rst
=> list_of_events: Add "mail_index_recreated" event to mail-index events

source/admin_manual/event_design.rst, source/configuration_manual/event_export.rst, source/configuration_manual/event_filter.rst, source/configuration_manual/stats/index.rst, source/settings/core.rst
On top of: https://github.com/dovecot/documentation/pull/100
=> New event filter language

source/configuration_manual/mail_location/obox/dictmap_cassandra.rst
Document cassandra TLS settings.  JIRA DOV-4079
=> dictmap_cassandra.rst: Document TLS settings

source/admin_manual/list_of_events.rst
=> list_of_events: Add hibernation events

source/admin_manual/submission_server.rst
* unified style (used list)
* added submission_client_workarounds with proper formatting
=> Update Submission Server documentation

requirements.txt, source/conf.py, source/configuration_manual/namespace/index.rst, source/settings/core.rst
=> Add missing core settings

source/settings/core.rst
merged the original commit a bit too early
=> settings: mail_fsync - Fix indentation

source/configuration_manual/event_filter.rst, source/installation_guide/upgrading/from-2.3-to-2.3.12.rst, source/installation_guide/upgrading/index.rst
=> Event syntax

source/admin_manual/list_of_events.rst
=> list_of_events: Add fs_dictmap_max_bucket_changed event

source/admin_manual/list_of_events.rst, source/configuration_manual/mail_location/obox/dictmap.rst
=> list_of_events: Document fs_dictmap_dict_write_uncertain event

source/admin_manual/list_of_events.rst, source/configuration_manual/mail_location/obox/dictmap_cassandra_objectid.rst
=> list_of_events: Add fs_dictmap_empty_bucket_iterated event

source/admin_manual/known_issues/centos8_mailhome.rst
=> missing quotes

source/configuration_manual/config_file/config_file_syntax.rst
=> config_file_syntax: Explain environment variables

source/configuration_manual/authentication/master_users.rst, source/settings/plugin/acl.rst, source/settings/plugin/aclPlugins.rst
=> Add acl_ignore_namespace setting

source/configuration_manual/mail_location/obox/http_storages.rst
=> configuration_manual: http_storages: Add information about retry wait on errors

source/settings/core.rst
Fixes duplicate text issue, and proposes various editorial changes
=> Mail attachment detection options fixes

source/configuration_manual/mail_location/obox/compression.rst, source/configuration_manual/zlib_plugin.rst, source/settings/plugin/zlib-plugin.rst
This updates the docs to be consistent with each other and reality.
FWIW, I looked the code in core and there are some interesting assumptions about what values are valid for levels.  I have some WIP code to make that stuff sane, but that'll have to wait for next week at the very least.  So, this PR should be considered stand-alone.
=> Consistify zlib documentation

source/configuration_manual/mail_location/obox/scality_sproxyd.rst
=> configuration_manual: obox/scality_sproxyd - Add avoid_423 setting

source/configuration_manual/sieve/extensions/enotify.rst, source/settings/pigeonhole-ext/enotify.rst, source/settings/pigeonhole-ext/index.rst
=> sieve: Document enotify extension

source/configuration_manual/mail_crypt_plugin.rst, source/settings/plugin/fs-compress-plugin.rst
=> settings/fs-compress-plugin: Improve formatting

source/configuration_manual/mail_location/obox/s3.rst
=> s3: Clarify that only AWS S3 is supported

source/configuration_manual/replication.rst, source/settings/plugin/replication-plugin.rst
=> replication: Import replication from wiki

source/configuration_manual/authentication/password_databases_passdb.rst
Clean up duplicated paragraph in the docs.
=> Clean-up paragraph duplication

source/configuration_manual/shared_mailboxes/cluster_setup.rst
=> Import imapc_features documentation  and mention it in shared mailbox page

source/admin_manual/list_of_events.rst
- mail_opened
- mail_expunged
- mail_expunge_requested
- mail_cache_lookup
=> list_of_events: Add new mail events

source/configuration_manual/mail_location/obox/compression.rst, source/configuration_manual/protocols/imap_server.rst, source/configuration_manual/zlib_plugin.rst, source/installation_guide/upgrading/from-2.3-to-2.3.x.rst, source/settings/plugin/fs-compress-plugin.rst, source/settings/plugin/imap-compress-plugin.rst, source/settings/plugin/imap-zlib-plugin.rst, source/settings/plugin/zlib-plugin.rst
=> Update documentation for compression levels

source/settings/core.rst
=> settings/core: Document ssl_cipher_suites

source/settings/plugin/vault-plugin.rst
Make clear this is OX Dovecot Pro only feature
=> Clean up vault plugin page

source/configuration_manual/service_configuration.rst, source/installation_guide/upgrading/from-2.3-to-2.3.x.rst
=> service_configuration: Document changes to auth-worker

source/settings/plugin/advanced/obox.rst
=> settings/plugin/advanced/obox: Add metacache_index_merging

source/configuration_manual/authentication/oauth2.rst
=> configuration/authentication/oauth2: Document openid_configuration_url

source/developer_manual/design/arrays.rst
=> developer_manual: Add array_idx_elem() and array_foreach_elem()

source/configuration_manual/mail_location/imapc/index.rst, source/configuration_manual/shared_mailboxes/cluster_setup.rst
=> configuration_manual: shared_mailboxes: Improve instructions and add acl to imapc_features

source/configuration_manual/authentication/password_schemes.rst
=> configuration_manual: Fix default doveadm-pw scheme to CRYPT

source/configuration_manual/lazy_expunge_plugin.rst
=> configuration_manual/lazy_expunge_plugin: Add lazy_expunge_exclude

source/configuration_manual/authentication/dict.rst, source/configuration_manual/authentication/oauth2.rst, source/configuration_manual/dict/index.rst, source/configuration_manual/dict/proxy.rst, source/configuration_manual/imap_metadata.rst, source/configuration_manual/mail_location/obox/dictmap.rst, source/configuration_manual/notify_status_plugin.rst, source/configuration_manual/quota/quota_dict.rst, source/configuration_manual/shared_mailboxes/cluster_setup.rst, source/configuration_manual/sieve/dict.rst, source/settings/plugin/acl.rst, source/settings/plugin/notify-status-plugin.rst
Obsoletes wiki pages:
https://wiki.dovecot.org/Dictionary
https://wiki.dovecot.org/Dict
=> Import Dictionary pages from wiki

source/admin_manual/list_of_events.rst
Also remove username from common fields as it is no longer common.
=> events: Add new dict_created and dict_destroyed events

source/configuration_manual/nfs.rst
Remove things that are obsolete or really not recommended at all.
Also remove suggestions that aren't clearly explained.
=> configuration_manual/nfs: Rewrite the page

source/admin_manual/list_of_events.rst
Also add missing dest_ip for http_request_*.
=> list_of_events: Fix client/server_connection_* events' fields

source/configuration_manual/authentication/oauth2.rst
=> configuration_manual/authentication/oauth2: Document .. escaping

source/configuration_manual/virtual_attachments_plugin.rst, source/configuration_manual/virtual_plugin.rst, source/settings/plugin/advanced/obox.rst
=> virtual & virtual-attachments documentation updates

source/admin_manual/lua.rst
=> admin_manual/lua: Add dict API documentation

source/configuration_manual/service_configuration.rst
=> configuration_manual: document lowering priority for indexer-worker

source/admin_manual/error_codes.rst, source/admin_manual/migrating_mailboxes.rst
=> admin_manual: Add page on doveadm/dsync error codes

source/admin_manual/submission_server.rst, source/configuration_manual/protocols/imap_server.rst, source/settings/core.rst
=> settings: imap_urlauth_host is required for URLAUTH to be active

source/configuration_manual/howto/chasquid_and_dovecot_sasl.rst, source/configuration_manual/howto/exim_and_dovecot_sasl.rst
Someone clearly in love with Postfix ;-)
=> Fixing mind-slip titles to match both intent and filename

source/configuration_manual/mail_location/Maildir/index.rst
=> maildir: Document conflicting dovecot.list.index behavior

source/configuration_manual/stats/index.rst
doveadm stats add group-by parameter fix and examples of doveadm stats add/remove
=> Stats modify ammendments

source/configuration_manual/shared_mailboxes/cluster_setup.rst, source/configuration_manual/shared_mailboxes/cluster_setup_example.rst
=> configuration_manual/shared_mailboxes/cluster_setup: Add delay-login to imapc_features

.gitignore, source/admin_manual/submission_server.rst, source/settings/core.rst
=>  Add description of implicit-auth-external value for submission_client_workarounds setting.

source/settings/plugin/obox-plugin.rst
=> settings/obox: obox_index_fs can now be used with fs-posix

source/admin_manual/list_of_events.rst
=> admin_manual/list_of_events: Add new cmd_args and cmd_human_args to SMTP server command events.

source/configuration_manual/quota/index.rst
=> configuration_manual/quota: Clarify how shared namespaces are counted

source/admin_manual/list_of_events.rst
DOV-4949 (subtask of DOV-4736)
=> admin_manual/list_of_events: Add more fields to proxy_session_finished

source/admin_manual/list_of_events.rst
=> list_of_events: Remove mail_cache_lookup_finished event

source/configuration_manual/dovecot_ssl_configuration.rst
noticed that the link to the SNIClientSupport-Page was broken.
=> [minor] update SNI Client Support reference

source/configuration_manual/howto/procmail.rst
=> configuration_manual/howto/procmail: Move wiki page to documentation

source/admin_manual/event_reasons.rst
=> event_reasons: Remove many of the mail:* reasons

.github/actions/spelling/expect.txt, README.md, source/_ext/dovecot_sphinx.py, source/configuration_manual/mail_location/obox/dictmap_cassandra.rst, source/settings/plugin/sql-cassandra.rst, source/settings/plugin/sql-mysql.rst, source/settings/plugin/sql-postgresl.rst, source/settings/plugin/sql-sqlite.rst
Extends #294 to adapt/use the new Dovecot Sphinx setting directives.
=> Driver settings

source/settings/core.rst
=> Document the new lmtp_verbose_replies setting.

source/admin_manual/event_reasons.rst
=> event_reasons: Remove mailbox:search

source/configuration_manual/mail_location/index.rst
=> mail_location: Add note about NO-NOSELECT with LAYOUT=index

source/configuration_manual/zlib_plugin.rst
=> zlib_plugin: Indicate where maildirlock is found

source/admin_manual/list_of_events.rst
=> Cache lookup insert

source/configuration_manual/acl.rst
=> configuration_manual/acl: Mark global acl directory removed

.github/workflows/main.yml
=> Per branch workflow 2.3

.github/workflows/main.yml
=> Per branch workflow

.github/actions/spelling/expect.txt, source/configuration_manual/plugins/nfs_hostchange_plugin.rst
=> nfs_hostchange_plugin: Add documentation

source/admin_manual/lua.rst
=> admin_manual: lua: Document the interface to dovecot's lib-http

source/admin_manual/lua.rst
=> Cherry-pick v2.3: admin_manual: lua: Document the interface to dovecot's lib-http

.github/actions/spelling/expect.txt, source/configuration_manual/plugins/nfs_hostchange_plugin.rst
=> Nfs hostchange 2.3

source/settings/core.rst
v3.0 changed in https://github.com/dovecot/documentation/pull/430
=> v2.3: settings/core: ssl_options - Fix [no_]compression version numbering

.github/actions/spelling/expect.txt, source/admin_manual/login_processes.rst, source/admin_manual/post_login_scripting.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst, source/settings/core.rst
=> Remove login_access_sockets

source/developer_manual/design/dict_protocol.rst
=> developer_manual: dict - COMMIT_ASYNC is removed in v2.4/v3.0

source/settings/plugin/mail-crypt-plugin.rst
=> mail-crypt-plugin: mail_crypt_require_encrypted_user_key is now boolean

source/admin_manual/login_processes.rst, source/configuration_manual/director_settings.rst, source/settings/core.rst
=> Dov 5191/add login auth socket path setting

source/configuration_manual/plugins/nfs_hostchange_plugin.rst
Fix version for nfs hostchange.
=> nfs_hostchange_plugin: Fix versions

source/admin_manual/lua.rst
=> admin_manual/lua: Document more http client settings

source/admin_manual/lua.rst
=> CHERRY-PICK v2.3 - lua: Fix http-client version

source/configuration_manual/authentication/password_schemes.rst, source/settings/core.rst
=> Weak schemes

source/admin_manual/lua.rst
=> Lua dns-client

source/configuration_manual/virtual_plugin.rst
=> configuration_manual/virtual: Remove text about imapsieve problems

source/admin_manual/submission_server.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> installation_guide/Upgrading: Update page

source/settings/core.rst
=> settings/core: Add dsync_features=no-header-hashes

source/configuration_manual/service_configuration.rst
=> configuration_manual/service_configuration: Add dict-expire service

source/settings/plugin/mail-crypt-plugin.rst
=> Mail crypt boolean

source/settings/plugin/mail-crypt-plugin.rst
=> Mail crypt boolean 2.3

source/configuration_manual/service_configuration.rst, source/developer_manual/design/processes.rst
=> ipc service is removed in v2.4/v3.0

source/settings/plugin/sql-sqlite.rst
=> sql-sqlite: Fix versionchanged to text to reflect correct version.

source/configuration_manual/plugins/dumpster_config.rst
=> Dumpster fixes

source/configuration_manual/plugins/dumpster_config.rst
=> Dumpster 2.3

source/configuration_manual/authentication/dict.rst, source/configuration_manual/authentication/proxies.rst, source/configuration_manual/dovecot_ssl_configuration.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> Db dict format

source/configuration_manual/authentication/auth_policy.rst
=> auth policy: Document fail_type

source/admin_manual/doveadm_mailbox_commands.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> doveadm: Document change in user parameter handling in mail commands

source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> upgrading: Mention auth_allow_cleartext

source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> upgrading: Fix ref syntax

source/admin_manual/obox/index.rst
=> admin_manual_obox: Add mention of doveadm metacache pull

source/man/Makefile
Now works with non-GNU make as well
=> source/man: Makefile - Make portable

source/configuration_manual/authentication/master_users.rst, source/settings/core.rst
=> settings: Mark master_user_separator setting removed

source/configuration_manual/authentication/master_users.rst, source/settings/core.rst
=> 2.3 cherry-pick: Master user separator

source/configuration_manual/plugins/nfs_hostchange_plugin.rst
=> configuration_manual: Fix syntax typo on nfs_hostchange page

.github/actions/spelling/expect.txt, source/configuration_manual/push_notification.rst
=> DOV-5639: Add chronos push notification plugin documentation

source/conf.py, source/index.rst, source/obox-man/Makefile, source/obox-man/doveadm-fscache.1.rst.in, source/obox-man/doveadm-metacache.1.rst.in, source/obox-man/doveadm-obox.1.rst.in, source/obox-man/global-options-formatter.inc.in, source/obox-man/global-options.inc.in, source/obox-man/index.rst, source/obox-man/option-A.inc.in, source/obox-man/option-F-file.inc.in, source/obox-man/option-S-socket.inc.in, source/obox-man/option-u-user.inc.in, source/obox-man/option-x.inc.in, source/obox-man/reporting-bugs.inc.in
=> Add obox plugin manpages

source/admin_manual/list_of_events.rst, source/configuration_manual/config_file/config_variables.rst, source/configuration_manual/dovecot_ssl_configuration.rst, source/configuration_manual/haproxy/index.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst, source/settings/core.rst
=> Login clarify fields

source/configuration_manual/mail_location/obox/http_storages.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> configuration_manual: http_storages: Remove deprecated options

.github/workflows/ci.yml, .github/workflows/main.yml
Uses new dovecot specific builder
=> github: Build documentation and manpage tarballs

.github/workflows/main.yml
It gets prepended with workspace dir
=> github: Add missing / to base_dir

source/configuration_manual/push_notification.rst
This is https://github.com/dovecot/documentation/pull/593 that was accidentally closed.
=> Clarify chronos driver

source/configuration_manual/push_notification.rst
Cherry pick https://github.com/dovecot/documentation/pull/603 to release-2.3
=> CHERRY-PICK 2.3: Rename chronos plugin

source/configuration_manual/authentication/password_schemes.rst
…ator along with ARGON2I and ARGON2ID
=> auth: Add support for ARGON2 scheme

.github/actions/spelling/expect.txt, .github/workflows/spelling.yml, source/admin_manual/chrooting.rst, source/admin_manual/errors/chgrp_no_perm.rst, source/admin_manual/errors/index.rst, source/admin_manual/errors/socket_unavailable.rst, source/admin_manual/errors/time_moved_backwards.rst, source/configuration_manual/authentication/digest-md5.rst, source/configuration_manual/authentication/winbind.rst
=> Remove wiki 2.3

source/configuration_manual/forwarding_parameters.rst
=> forwarding_parameters: Fix ID command example

.github/actions/spelling/expect.txt, source/index.rst, source/man/dovecot.1.rst.in, source/obox-man/doveadm-fscache.1.rst.in, source/pigeonhole-man/Makefile, source/pigeonhole-man/doveadm-sieve.1.rst.in, source/pigeonhole-man/global-options-formatter.inc.in, source/pigeonhole-man/global-options.inc.in, source/pigeonhole-man/index.rst, source/pigeonhole-man/option-A.inc.in, source/pigeonhole-man/option-F-file.inc.in, source/pigeonhole-man/option-S-socket.inc.in, source/pigeonhole-man/option-d.inc.in, source/pigeonhole-man/option-o.inc.in, source/pigeonhole-man/option-u-user.inc.in, source/pigeonhole-man/option-x-ext.inc.in, source/pigeonhole-man/pigeonhole.7.rst.in, source/pigeonhole-man/reporting-bugs.inc.in, source/pigeonhole-man/sieve-dump.1.rst.in, source/pigeonhole-man/sieve-filter.1.rst.in, source/pigeonhole-man/sieve-test.1.rst.in, source/pigeonhole-man/sievec.1.rst.in
=> Pigeonhole man

source/admin_manual/error_codes.rst, source/admin_manual/list_of_events.rst, source/admin_manual/obox/index.rst, source/settings/plugin/obox-plugin.rst
=> admin_manual/list_of_events: Add metacache pull events

source/admin_manual/cassandra/cassandra.rst
Fixups to https://github.com/dovecot/documentation/pull/638
=> admin_manual/cassandra: Minor fixups to previous change

.github/actions/spelling/expect.txt, source/admin_manual/migrating_mailboxes.rst, source/configuration_manual/mail_location/imapc/index.rst, source/configuration_manual/shared_mailboxes/cluster_setup.rst, source/configuration_manual/shared_mailboxes/cluster_setup_example.rst
=> DOV-5514: Describe obsolete imapc_features

source/configuration_manual/ssl_configuration.rst
=> configuration_manual: Mention OpenSSL 1.1 requirement for JA3

source/configuration_manual/authentication/lua_based_authentication.rst, source/configuration_manual/push_notification.rst
=> configuration_manual/push_notification: Update examples to use dovecot.http.client

.github/actions/spelling/expect.txt, README.md, requirements.txt, source/_ext/dovecot_sphinx.py, source/_static/custom.css, source/admin_manual/list_of_events.rst, source/conf.py, source/installation_guide/upgrading/from-2.3-to-2.3.x.rst, source/settings/advanced.rst
Think this has reached a point of beta, so we can begin to iterate through design decisions, fact-checking, etc.
=> Event list directive

.github/actions/spelling/expect.txt, source/cluster-man/Makefile, source/cluster-man/doveadm-cluster-backend.1.rst.in, source/cluster-man/doveadm-cluster-geodb.1.rst.in, source/cluster-man/doveadm-cluster-group.1.rst.in, source/cluster-man/doveadm-cluster-kick.1.rst.in, source/cluster-man/doveadm-cluster-localdb.1.rst.in, source/cluster-man/doveadm-cluster-site.1.rst.in, source/cluster-man/doveadm-cluster-user.1.rst.in, source/cluster-man/doveadm-cluster.1.rst.in, source/cluster-man/dovecot-cluster.7.rst.in, source/cluster-man/global-options-formatter.inc.in, source/cluster-man/global-options.inc.in, source/cluster-man/index.rst, source/cluster-man/option-A.inc.in, source/cluster-man/option-F-file.inc.in, source/cluster-man/option-u-user.inc.in, source/cluster-man/reporting-bugs.inc.in, source/conf.py, source/manual_pages.rst, source/obox-man/index.rst, source/pigeonhole-man/index.rst
=> Cluster man

source/configuration_manual/event_filter.rst, source/man/doveconf.1.rst.in
=> man/doveconf: Remove -m parameter

source/admin_manual/login_processes.rst, source/settings/core.rst
=> Rename login_auth_socket_path to login_socket_path

.github/workflows/spectral.yml
=> GHA: Add spectral scan

source/configuration_manual/authentication/password_database_extra_fields.rst, source/configuration_manual/authentication/user_database_extra_fields.rst
=> configuration_manual/authentication: Document event_ extra field

source/configuration_manual/fts/dovecot.rst, source/configuration_manual/fts/index.rst, source/man/doveadm-fts.1.rst.in, source/settings/plugin/fts-dovecot-plugin.rst
=> configuration_manual/fts: Add "doveadm fts check" command details

source/_ext/dovecot_sphinx.py, source/admin_manual/list_of_events.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> admin_manual/list_of_events: Add new fields to mail_user_session_finished

source/configuration_manual/stats/index.rst, source/configuration_manual/stats/openmetrics.rst
=> stats: Indicate that fields are now exported with openmetrics too

source/admin_manual/list_of_events.rst
=> admin_manual/list_of_events: Add login_aborted

source/configuration_manual/service_configuration.rst, source/settings/core.rst
=> settings, configuration_manual: Update idle_kill and default_idle_kill

source/admin_manual/event_design.rst, source/configuration_manual/event_export.rst, source/configuration_manual/event_filter.rst, source/configuration_manual/stats/index.rst
=> global: Finish renaming bytes_in/out, out net_in/out_bytes

.github/actions/spelling/expect.txt, source/man/doveadm-save.1.rst.in, source/man/doveadm-search-query.7.rst.in
=> doveadm-save new parameters

.github/actions/spelling/expect.txt, source/configuration_manual/forwarding_parameters.rst
=> configuration_manual/forwarding_parameters: Document DESTNAME/x-connected-name

source/cluster-man/doveadm-cluster-backend.1.rst.in, source/cluster-man/doveadm-cluster-site.1.rst.in
=> cluster-man: Document uuid option for site and backend

source/admin_manual/lua.rst, source/configuration_manual/authentication/lua_based_authentication.rst, source/configuration_manual/push_notification.rst
=> auth: Document argument passing to Lua scripts

source/configuration_manual/event_filter.rst
=> event_filter: Document escaping wildcard characters

.github/actions/spelling/expect.txt, source/admin_manual/index.rst, source/admin_manual/process_titles.rst, source/settings/core.rst
=> admin_manual: Add process_titles

.github/actions/spelling/expect.txt, source/configuration_manual/authentication/oauth2.rst
=> authentication/oauth2: Update documentation

source/configuration_manual/authentication/ldap_settings_auth.rst
=>  Remove "userdb_warning_disable" from LDAP settings

source/configuration_manual/stats/index.rst
=> stats: Indicate change in label name limitations

.github/actions/spelling/expect.txt, source/configuration_manual/howto/director_with_lua.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> Document how to use Lua to replace director.

source/configuration_manual/event_export.rst, source/configuration_manual/stats/index.rst
=> 2.3 cherry-pick: configuration_manual: Fix name -> cmd_name event parameters

source/configuration_manual/event_export.rst, source/configuration_manual/stats/index.rst
=> configuration_manual: Fix name -> cmd_name event parameters

source/configuration_manual/mail_location/obox/dictmap.rst
=> dictmap: Remove nonexistent no-store-orig-path setting

source/cluster-man/doveadm-cluster-site.1.rst.in
=> cluster-man: Add cluster site init command

source/_ext/dovecot_sphinx.py, source/configuration_manual/notify_status_plugin.rst, source/settings/plugin/notify-status-plugin.rst
=> notify-status: Update notify-status configuration and settings

.github/actions/spelling/expect.txt, source/admin_manual/obox/storage_side_metadata.rst, source/configuration_manual/mail_location/obox/azure.rst, source/configuration_manual/mail_location/obox/index.rst
=> obox: Add initial azure driver documentation

source/configuration_manual/howto/rootless.rst
=> howto: Rootless

source/cluster-man/doveadm-cluster-site.1.rst.in, source/cluster-man/doveadm-cluster-tag.1.rst.in, source/cluster-man/doveadm-cluster.1.rst.in
=> cluster: Document cluster tag management commands

source/configuration_manual/mail_location/obox/azure.rst
=> obox: azure: Add debugging instructions

source/obox-man/doveadm-metacache.1.rst.in
=> obox-man: metacache list - Document -f option

.github/actions/spelling/expect.txt, source/configuration_manual/authentication/oauth2.rst
Document how to use microsoft identity platform.
=> authentication: oauth2 - Add Microsoft Identity Platform hint

source/configuration_manual/event_export.rst, source/man/doveadm-stats.1.rst.in
=> Document event exporter transport file

source/configuration_manual/mail_location/obox/dictmap_cassandra.rst
There was some wrongness in the example config
=> Cassandra example fix

source/configuration_manual/event_export.rst, source/configuration_manual/stats/index.rst
DOV-6003 & parts of DOV-6031 already
=> settings redesign: configuration_manual: Update metrics and event exporters

source/admin_manual/migrating_mailboxes.rst, source/configuration_manual/dict/index.rst, source/configuration_manual/imap_metadata.rst, source/configuration_manual/mail_crypt_plugin.rst, source/configuration_manual/protocols/imap_server.rst, source/settings/core.rst
=> global: Rename mail_attribute_dict to mail_attribute

source/admin_manual/ssl/certificate_creation.rst
- Fix the link to mkcert.sh
- Fix some formatting
- Remove a stray "|"
=> Fix minor documentation issues

source/configuration_manual/authentication/ldap.rst
Hi the text and they link it points to it's inverted
=> Links don't match text

source/admin_manual/list_of_events.rst, source/admin_manual/login_processes.rst, source/configuration_manual/mail_location/Maildir/index.rst, source/configuration_manual/namespace/index.rst, source/configuration_manual/service_configuration.rst, source/configuration_manual/shared_mailboxes/public_shared.rst, source/installation_guide/upgrading/from-1.2-to-2.0.rst, source/settings/core.rst, source/settings/pigeonhole.rst, source/settings/plugin/notify-status-plugin.rst, source/settings/types.rst
=> config-rewrite: Service settings

.github/actions/spelling/expect.txt, source/configuration_manual/mail_crypt_plugin.rst, source/man/doveadm-dump.1.rst.in, source/settings/plugin/mail-crypt-plugin.rst
=> mail-crypt: Document X448 and X25519 algorithms

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, source/admin_manual/filesystem_permission.rst, source/configuration_manual/acl.rst, source/configuration_manual/dict/index.rst, source/configuration_manual/shared_mailboxes/cluster_setup.rst, source/configuration_manual/shared_mailboxes/cluster_setup_example.rst, source/configuration_manual/shared_mailboxes/public_shared.rst, source/configuration_manual/shared_mailboxes/shared_mailboxes.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst, source/man/doveadm-acl.1.rst.in, source/settings/plugin/acl-plugin.rst
=> acl: Update ACL documentation

source/admin_manual/filesystem_permission.rst, source/configuration_manual/authentication/auth_policy.rst, source/configuration_manual/authentication/authentication_via_remote_imap_server.rst, source/configuration_manual/authentication/caching.rst, source/configuration_manual/authentication/ldap_settings_auth.rst, source/configuration_manual/authentication/ldap_settings_common.rst, source/configuration_manual/authentication/master_users.rst, source/configuration_manual/authentication/pam.rst, source/configuration_manual/authentication/passwd_file.rst, source/configuration_manual/authentication/password_databases_passdb.rst, source/configuration_manual/authentication/restrict_access.rst, source/configuration_manual/authentication/user_databases_userdb.rst, source/configuration_manual/howto/rootless.rst, source/configuration_manual/howto/simple_virtual_install.rst, source/configuration_manual/howto/virtual_user_flat_files_postfix.rst, source/configuration_manual/mail_location/obox/amazon_s3.rst, source/configuration_manual/mail_location/obox/fscache.rst, source/configuration_manual/mail_location/obox/http_storages.rst, source/configuration_manual/virtual_plugin.rst, source/configuration_manual/virtual_users.rst, source/installation_guide/upgrading/from-2.2-to-2.3.rst, source/man/doveadm-user.1.rst.in, source/settings/core.rst, source/settings/types.rst
DOV-6306 & DOV-6424
On top of https://github.com/dovecot/documentation/pull/826
=> settings redesign: auth passdb/userdb blocks

source/settings/plugin/obox-plugin.rst
=> settings/plugin/obox: Add metacache_forced_refresh_interval

source/configuration_manual/config_file/config_variables.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst, source/settings/core.rst
=> config_variables: Document system: key

source/admin_manual/list_of_events.rst, source/cluster-man/doveadm-cluster-backend.1.rst.in, source/cluster-man/doveadm-cluster-site.1.rst.in, source/cluster-man/doveadm-cluster-tag.1.rst.in
=> cluster new events & uuid rename

source/admin_manual/debugging/debugging_rawlog.rst, source/admin_manual/post_login_scripting.rst, source/configuration_manual/authentication/ldap_userdb.rst, source/configuration_manual/authentication/pam.rst, source/configuration_manual/authentication/passwd.rst, source/configuration_manual/authentication/passwd_file.rst, source/configuration_manual/authentication/proxies.rst, source/configuration_manual/authentication/static_password_database.rst, source/configuration_manual/authentication/user_database_extra_fields.rst, source/configuration_manual/dovecot_ssl_configuration.rst, source/configuration_manual/home_directories_for_virtual_users.rst, source/configuration_manual/howto/virtual_user_flat_files_postfix.rst, source/configuration_manual/mail_crypt_plugin.rst, source/configuration_manual/quick_configuration.rst, source/configuration_manual/quota/index.rst, source/configuration_manual/service_configuration.rst, source/configuration_manual/shared_mailboxes/cluster_setup_example.rst, source/configuration_manual/system_users.rst, source/configuration_manual/virtual_users.rst, source/installation_guide/upgrading/from-2.2-to-2.3.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst, source/man/doveadm-user.1.rst.in, source/man/doveconf.1.rst.in, source/man/dovecot.1.rst.in, source/settings/core.rst, source/settings/plugin/mail-crypt-plugin.rst, source/settings/types.rst
=>  settings redesign: Convert SSL setting paths to a "file" setting type 

source/settings/advanced.rst, source/settings/core.rst
=> settings: Replace doveadm_http_rawlog_dir with http_server_rawlog_dir and doveadm_server named filter

source/cluster-man/doveadm-cluster-group.1.rst.in, source/cluster-man/doveadm-cluster-user.1.rst.in, source/settings/cluster.rst
=> settings/cluster: Update cluster_backend_test_username

source/admin_manual/errors/socket_unavailable.rst, source/admin_manual/login_processes.rst, source/configuration_manual/authentication/proxies.rst, source/configuration_manual/performance_tuning.rst, source/configuration_manual/proxy_settings.rst, source/configuration_manual/service_configuration.rst, source/configuration_manual/sieve/managesieve/configuration.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst
=> DOV-6379: Rename `service_service_count` -> `service_restart_request_count`

source/admin_manual/test_installation.rst, source/configuration_manual/howto/imapc_proxy.rst, source/configuration_manual/howto/virtual_user_flat_files_postfix.rst, source/configuration_manual/protocols/lmtp_server.rst, source/configuration_manual/service_configuration.rst, source/settings/core.rst
=> Inet listener address -> listen change

source/settings/cluster.rst
=> settings/cluster: Add cluster_proxy_check_backends

source/configuration_manual/authentication/passwd_file.rst, source/configuration_manual/authentication/password_databases_passdb.rst, source/configuration_manual/authentication/user_databases_userdb.rst
=> settings redesign: Use a single generic passdb/userdb_fields

.github/actions/spelling/expect.txt, source/_ext/dovecot_sphinx.py, source/configuration_manual/authentication/authentication_mechanisms.rst, source/configuration_manual/authentication/oauth2.rst
=> authentication/oauth2: Update oauth2 documentation

source/configuration_manual/authentication/master_users.rst, source/configuration_manual/authentication/multiple_authentication_databases.rst, source/configuration_manual/authentication/password_database_extra_fields.rst, source/configuration_manual/authentication/password_schemes.rst, source/configuration_manual/authentication/prefetch_userdb.rst, source/configuration_manual/authentication/proxies.rst, source/configuration_manual/authentication/sql.rst, source/configuration_manual/authentication/user_extra_field.rst, source/configuration_manual/config_file/index.rst, source/configuration_manual/howto/dovecot_postgresql.rst, source/configuration_manual/mail_crypt_plugin.rst, source/man/dovecot.1.rst.in, source/man/option-A.inc.in, source/settings/core.rst, source/settings/plugin/sql-cassandra.rst, source/settings/plugin/sql-mysql.rst, source/settings/plugin/sql-postgresql.rst, source/settings/plugin/sql-sqlite.rst
=> sql config-rewrite

source/configuration_manual/authentication/multiple_authentication_databases.rst, source/configuration_manual/authentication/password_database_extra_fields.rst, source/configuration_manual/authentication/prefetch_userdb.rst, source/configuration_manual/authentication/proxies.rst, source/configuration_manual/authentication/sql.rst, source/configuration_manual/authentication/user_extra_field.rst, source/configuration_manual/config_file/index.rst, source/configuration_manual/fts/dovecot.rst, source/configuration_manual/howto/dovecot_postgresql.rst, source/configuration_manual/mail_crypt_plugin.rst, source/configuration_manual/mail_location/obox/amazon_s3.rst, source/configuration_manual/mail_location/obox/dictmap.rst, source/configuration_manual/mail_location/obox/fscache.rst, source/configuration_manual/mail_location/obox/s3.rst, source/configuration_manual/mail_location/obox/scality_cdmi.rst, source/configuration_manual/mail_location/obox/scality_sproxyd.rst, source/configuration_manual/plugins/fs-compress-plugin.rst, source/settings/plugin/fts-dovecot-plugin.rst
=> settings redesign: Auto-prefix with named list filter name

source/configuration_manual/authentication/lua_based_authentication.rst, source/configuration_manual/howto/director_with_lua.rst, source/configuration_manual/push_notification.rst, source/settings/core.rst, source/settings/plugin/mail-lua-plugin.rst
=> authentication/lua_based_authentication: Document new lua_path and lua_config settings

source/configuration_manual/acl.rst, source/configuration_manual/authentication/dict.rst, source/configuration_manual/config_file/index.rst, source/configuration_manual/dict/index.rst, source/configuration_manual/imap_metadata.rst, source/configuration_manual/lastlogin_plugin.rst, source/configuration_manual/mail_crypt_plugin.rst, source/configuration_manual/mail_location/obox/dictmap.rst, source/configuration_manual/mail_location/obox/dictmap_cassandra.rst, source/configuration_manual/notify_status_plugin.rst, source/configuration_manual/quota/index.rst, source/configuration_manual/quota/unified_quota_configuration.rst, source/configuration_manual/quota_clone_plugin.rst, source/configuration_manual/shared_mailboxes/cluster_setup_example.rst, source/configuration_manual/shared_mailboxes/shared_mailboxes.rst, source/configuration_manual/sieve/dict.rst, source/configuration_manual/sieve/plugins/extdata.rst, source/man/doveconf.1.rst.in, source/settings/core.rst, source/settings/plugin/acl-plugin.rst, source/settings/plugin/notify-status-plugin.rst, source/settings/plugin/quota-clone-plugin.rst
=> config rewrite: dict setting redesign

source/configuration_manual/authentication/allow_nets.rst, source/configuration_manual/authentication/domain_lost.rst, source/configuration_manual/authentication/kerberos.rst, source/configuration_manual/authentication/master_users.rst, source/configuration_manual/authentication/oauth2.rst, source/configuration_manual/authentication/static_password_database.rst, source/configuration_manual/authentication/static_user_database.rst, source/configuration_manual/howto/simple_virtual_install.rst, source/configuration_manual/mail_crypt_plugin.rst, source/configuration_manual/namespace/index.rst, source/configuration_manual/shared_mailboxes/cluster_setup_example.rst, source/configuration_manual/virtual_users.rst, source/settings/core.rst
=> Update static passdb and userdb examples and settings

source/configuration_manual/fs/index.rst, source/configuration_manual/fts/dovecot.rst, source/configuration_manual/fts/flatcurve.rst, source/configuration_manual/fts/index.rst, source/configuration_manual/fts/solr.rst, source/configuration_manual/mail_location/obox/amazon_s3.rst, source/configuration_manual/mail_location/obox/dictmap.rst, source/configuration_manual/mail_location/obox/s3.rst, source/configuration_manual/mail_location/obox/scality_cdmi.rst, source/configuration_manual/plugins/fs-compress-plugin.rst, source/installation_guide/upgrading/from-2.3-to-3.0.rst, source/man/doveadm-fs.1.rst.in, source/settings/plugin/fts-dovecot-plugin.rst, source/settings/plugin/fts-plugin.rst
=> settings redesign: Add fts named list filter

source/configuration_manual/authentication/passwd.rst, source/configuration_manual/quick_configuration.rst
=> passwd passdb config-rewrite update

source/configuration_manual/authentication/oauth2.rst
=> configuration_manual: oauth2 - Update settings syntax

source/configuration_manual/authentication/caching.rst, source/configuration_manual/authentication/pam.rst, source/configuration_manual/authentication/restrict_access.rst, source/settings/core.rst
=> pam passdb config-rewrite changes

source/admin_manual/list_of_events.rst, source/settings/plugin/sql-cassandra.rst
=> Cassandra: Improve logging consistency levels

source/settings/plugin/fts-plugin.rst
=> fts: Document fts_message_max_size setting

source/configuration_manual/mail_location/obox/dictmap.rst
=> configuration_manual/mail_location/obox/dictmap: Add aws-s3,s3 and azure examples

source/admin_manual/list_of_events.rst
=> config-rewrite: dict events: driver field is confusing

source/admin_manual/list_of_events.rst
=> admin/list_of_events: Remove cluster_backend_check_(started|finished) event

.vitepress/theme/custom.css, .vitepress/theme/index.js
=> vitepress: custom CSS to handle wide screens better

data/events.js, package-lock.json, package.json
=> list_of_events: Add tls_handshake_not_finished

data/settings.js
=> settings: Mark various settings as advanced

.github/actions/spelling/expect.txt, .vitepress/config.js, docs/core/config/delivery/lmtp.md, docs/core/config/delivery/mta.md, docs/core/config/mailbox/formats/maildir.md, docs/core/config/sql/cassandra.md, docs/core/config/ssl.md, docs/core/plugins/mail_crypt.md, docs/developers/design/dcrypt.md, lib/link_checker.js, lib/markdown.js, package-lock.json, package.json
Existing solution only checked RFC links; this code checks all external links.
=> Link verification for external links

data/settings.js, docs/core/plugins/quota.md
=> Add quota_max_mailbox_count setting

.vitepress/config.js, lib/markdown.js, lib/utility.js
=> Markdown config

data/settings.js, docs/core/plugins/quota.md
=> Add quota_mailbox_message_count setting

data/settings.js, docs/core/settings/syntax.md, docs/installation/upgrade/include/2.3-to-2.4.inc
=> settings: Add doveadm_config_version

data/settings.js, docs/core/man/include/global-options.inc, docs/installation/upgrade/include/2.3-to-2.4.inc
DOV-6785
On top of https://github.com/dovecot/documentation/pull/909
=> settings: Add dovecot_storage_version

.vitepress/local.js.dist, lib/markdown.js, lib/utility.js
This supersedes (replaces) #943
=> Markdown extend

docs/core/plugins/last_login.md, docs/core/plugins/quota_clone.md
=> DOV-6758: Allow references to specific pages

data/settings.js
=> settings: Update OpenSSL DH param generation command example

docs/installation/upgrade/include/2.3-to-2.4.inc
=> upgrade: SETQUOTA / quota_set is removed

.github/actions/spelling/expect.txt, source/configuration_manual/config_file/index.rst
=> configuration_manual/config_file: Add group includes

data/events.js
=> data/events: Add connection_limit

data/settings.js, data/updates.js
=> data: Add auth_internal_failure_delay setting

.github/actions/spelling/expect.txt, docs/core/config/sql/cassandra.md, docs/installation/upgrade/include/2.3-to-2.4.inc
=> Remove Cassandra ssl_verify=cert-dns

lib/utility.js, util/generate_man.js
=> generate_man: Find includes in multiple places

components/EventsComponent.vue, components/SettingsComponent.vue, data/settings.js, lib/data/events.data.js, lib/data/settings.data.js, util/generate_man.js
Necessary changes to the core project  to support the config-rewrite changes.
=> DOV-6867: Adapt Settings Framework

.github/actions/spelling/expect.txt, source/configuration_manual/mail_location/imapc/index.rst
=> 2.3.22: imapc: Add imapc_features=no-qresync

data/updates.js, docs/core/config/statistics.md
=> config/statistics: Add discrete modifiers

.github/workflows/main.yml
=> github: Only match tags that start with 2

.github/actions/spelling/expect.txt, data/events.js, data/settings.js, data/updates.js, docs/core/admin/chrooting.md, docs/core/config/auth/caching.md, docs/core/config/auth/databases/imap.md, docs/core/config/auth/databases/oauth2.md, docs/core/config/auth/databases/pam.md, docs/core/config/auth/databases/passwd.md, docs/core/config/auth/proxies.md, docs/core/config/dict.md, docs/core/config/guides/quick.md, docs/core/config/shared_mailboxes.md, docs/core/man/doveconf.1.md, docs/core/plugins/last_login.md, docs/core/plugins/quota_clone.md, docs/core/plugins/sieve.md, docs/core/settings/syntax.md, docs/core/settings/variables.md, docs/howto/restrict_access.md
Last batch of changes!
Requires:
- #952 
- #953 
- #958 
- #961 
- #963 
- #967 
- #981 
Closes DOV-6868 eventually.
=> DOV-6868: Port config-rewrite changes - Part VII (last one)

data/settings.js, data/updates.js, docs/core/admin/rawlog.md, docs/core/config/auth/databases/ldap.md, docs/core/config/auth/databases/passwd_file.md, docs/core/config/auth/passdb.md, docs/core/config/auth/userdb.md, docs/howto/convert_password_schemes.md, docs/howto/imapc_proxy.md, docs/installation/upgrade/include/2.2-to-2.3.inc, docs/installation/upgrade/include/2.3-to-2.4.inc
=> settings redesign: passdb/userdb: Remove default_fields and override_fields

data/settings.js, docs/core/config/execute.md, docs/core/plugins/welcome.md
=> settings redesign: lib-program-client

data/settings.js, docs/core/config/auth/passdb.md, docs/core/config/auth/penalty.md
=> auth: Clarify how auth failure delay settings interact

data/settings.js, docs/core/admin/migration.md, docs/core/plugins/apparmor.md, docs/core/plugins/charset_alias.md, docs/core/plugins/last_login.md, docs/core/plugins/mail_log.md, docs/core/plugins/trash.md
=> config-rewrite: Other plugins

.github/actions/spelling/expect.txt, data/settings.js
=> data: settings - Add cdb_path

data/settings.js, docs/core/plugins/last_login.md, docs/core/plugins/quota_clone.md
DOV-6565 - change from dict_redis_ to redis_ in config-rewrite
=> DOV-6565: lib-dict: drop dict prefix from redis settings

data/updates.js, docs/core/config/namespaces.md, docs/core/config/shared_mailboxes.md, docs/core/plugins/quota.md
=> config-rewrite: Convert shared namespace prefix variables 

components/DoveadmComponent.vue
Applying similar styling to #1000
=> Doveadm summary styling

components/SettingsComponent.vue
Applying similar styling to https://github.com/dovecot/documentation/pull/1000
=> Settings summary styling

package-lock.json, package.json
=> Remove some dependencies

components/EventsComponent.vue
Changes were made locally and not pushed before MR was committed.
=> events: Add missing changes from GitHub Issue #1000

data/settings.js
=> settings: Remove hierarchy separator from imapc_list_prefix example

docs/core/config/dict.md
=> config/dict: Add path for dict-redis

data/settings.js
=> settings: Add default_* service settings

data/updates.js, docs/core/config/auth/databases/passwd_file.md
=> passwd-file: Document how to iterate database with variables

docs/core/settings/variables.md
=> variables: Add %{generate:} provider

docs/core/settings/variables.md
=> settings: variables - Document local and remote port

data/settings.js, docs/core/config/auth/databases/ldap.md, docs/core/config/dict.md, docs/core/config/sql/cassandra.md, docs/core/config/sql/mysql.md
=> SSL settings tags

data/settings.js
=> settings: Add ssl_client and ssl_server named filters

.github/actions/spelling/expect.txt, .gitignore, data/settings.js, docs/core/admin/guides/spam_reporting.md, docs/core/config/sieve/extensions/duplicate.md, docs/core/config/sieve/extensions/editheader.md, docs/core/config/sieve/extensions/spamtest_virustest.md, docs/core/config/sieve/extensions/vacation.md, docs/core/config/sieve/index.md, docs/core/config/sieve/managesieve.md, docs/core/plugins/imap_filter_sieve.md, docs/core/plugins/imap_sieve.md, docs/core/plugins/sieve.md, docs/core/plugins/sieve_extprograms.md, docs/howto/auto_forward.md, docs/howto/sieve.md, docs/howto/virtual/postfix.md, docs/installation/upgrade/include/2.4-removed-settings.inc
=> Sieve config rewrite

data/settings.js, docs/core/plugins/sieve.md
=> Sieve config rewrite (2)

components/SettingsComponent.vue
=> settings: Correctly display default settings for zero-ish values

data/settings.js
=> data/settings: Update mailbox setting to describe wildcards and renaming

docs/core/config/auth/passdb.md, docs/core/config/auth/userdb.md
=> auth: Clarify passdb/userdb lookup order

data/updates.js, docs/developers/design/auth_protocol.md
Details of channel binding are still missing.
=> design/auth_protocol: Add initial description of the v1.3 protocol

components/EventsComponent.vue
=> events: ID parameter needs value of k, not the letter k itself

data/events.js
=> data/events: Add proxy_session_reconnecting

data/lua.js, data/updates.js
=> lib-lua: Add set_forced_debug()

docs/core/config/sql/sqlite.md
=> sqlite: Remove obsolete note about the connect setting value

data/settings.js, docs/core/config/auth/databases/sql.md, docs/core/config/sql/mysql.md, docs/core/config/sql/postgresql.md, docs/core/config/sql/sqlite.md, docs/core/plugins/imap_sieve.md, docs/installation/upgrade/2.3-to-2.4.md, docs/installation/upgrade/include/2.4-converted-settings.inc, docs/installation/upgrade/include/2.4-external-configs.inc, docs/installation/upgrade/include/2.4-redesign.inc, docs/installation/upgrade/include/2.4-removed-settings.inc, docs/installation/upgrade/include/2.4-var-expand.inc
=> Improve upgrading documentation

docs/core/config/sieve/troubleshooting.md
=> sieve: Fix display of troubleshooting page (release-3.0.2)

.github/actions/spelling/expect.txt, docs/core/summaries/rfc.md
=> rfc - Add missing IMAP RFCs

source/configuration_manual/mail_crypt_plugin.rst
=> mail_crypt_plugin: Document some limitations on encryption algorithms

data/settings.js, data/updates.js, docs/core/config/auth/databases/sql.md
=> auth: Allow passdb/userdb sql to always use workers

data/settings.js
=> imapc_sasl_mechanisms: Document supported values

docs/core/summaries/rfc.md
=> rfc: Add RFC 8440 for IMAP LIST-MYRIGHTS capability

docs/core/plugins/mail_crypt.md
=> mail_crypt: Document some limitations on encryption algorithms

components/SettingsComponent.vue, lib/data/settings.data.js, lib/settings.js
=> settings: Allow types to hide default entry completely

docs/installation/upgrade/include/2.4-removed-other-features.inc
=> upgrade: local_name "multiple names" is no longer supported

components/SettingsComponent.vue, data/settings.js, docs/core/config/auth/userdb.md, lib/data/settings.data.js, lib/settings.js
=> Make some default settings required for certain types

data/settings.js, data/updates.js, docs/core/config/auth/include/anvil-algorithm.inc, docs/core/config/auth/include/anvil-overview.inc, docs/core/config/auth/include/anvil-problems.inc, docs/core/config/auth/include/anvil.inc, docs/core/config/auth/penalty.md, docs/core/config/include/login_process_high_performance.inc, docs/core/config/include/login_process_high_security.inc, docs/core/config/include/login_process_overview.inc, docs/core/config/include/login_process_socket_paths.inc, docs/core/config/login_processes.md, docs/core/config/service.md, docs/core/config/sieve/managesieve.md, docs/installation/upgrade/2.4-to-2.4.x.md
=> Dovecot Pro default changes

data/settings.js, data/updates.js, docs/installation/upgrade/2.4-to-2.4.x.md
It was accidentally merged too early.
=> Revert "Change mail_attachment_detection_options default"

data/doveadm.js, docs/core/man/doveadm-fts.1.md, docs/core/man/include/doveadm-fts-includes.inc, util/generate_man.js
* Allow man page to be overriden (fts check commands should not be displayed for CE, as it doesn't exist there)
* Add flatcurve documentation
=> Improved doveadm fts documentation

data/lua.js
=> lua: Document b64encode and b64decode

docs/installation/upgrade/2.3-to-2.4.md, docs/installation/upgrade/include/2.4-lua-http.inc
=> upgrade: Allow Pro docs to change Lua HTTP API upgrading title

data/lua.js, docs/developers/design/http.md
=> developers/design: Add internal lib-http response codes

data/settings.js
=> Lib dns 3.1.0

data/settings.js, data/updates.js, docs/installation/upgrade/2.4-to-2.4.x.md
=> CHERRY-PICK 3.1: upgrade: Add anvil socket changes #1220

data/settings.js
=> data/settings: Add fts_decoder_tika named filter

.github/actions/spelling/expect.txt, .github/actions/spelling/patterns.txt, data/settings.js, docs/core/config/sieve/extensions/extlists.md, docs/core/config/sieve/overview.md
JIRA: [DOV-7473](https://jira.open-xchange.com/browse/DOV-7473)
=> Sieve: Document support for extlists extension

data/settings.js
=> Add auth_master_socket_path

data/updates.js, docs/core/settings/syntax.md
=> settings: Describe the new delayed $SET variable expansion

data/updates.js, docs/core/settings/syntax.md
=> 3.1.0 CHERRY-PICK: config parser expands $SET too early

docs/core/settings/syntax.md
=> settings/syntax: Document $SET:filter/path/key

data/settings.js
=> data/settings: Add oauth2_token_expire_grace

docs/core/config/dict.md, docs/core/plugins/last_login.md
=> 3.1.0 cherry-pick: docs: dict-sql examples wrongly using pattern

.vitepress/config.js, .vitepress/theme/DovecotLayout.vue, .vitepress/theme/custom.css
=> Add warning if this is not release version
