source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/amzn/2/dovecot-2.3.9.2-rev1-fts-jp-kuromoji-plugin.repo
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/amzn/2/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/amzn/2/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/centos/6/dovecot-2.3.9.2-rev1-fts-jp-kuromoji-plugin.repo
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/centos/6/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/centos/6/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/centos/7/dovecot-2.3.9.2-rev1-fts-jp-kuromoji-plugin.repo
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/centos/7/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/centos/7/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/debian/buster/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/debian/stretch/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/debian/stretch/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/rhel/6/dovecot-2.3.9.2-rev1-fts-jp-kuromoji-plugin.repo
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/rhel/6/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/rhel/6/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/rhel/7/dovecot-2.3.9.2-rev1-fts-jp-kuromoji-plugin.repo
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/rhel/7/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/rhel/7/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/ubuntu/bionic/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/ubuntu/bionic/thirdparty
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/ubuntu/xenial/index.rst
source/installation_guide/dovecot_pro_releases/dovecot-2.3.9.2-rev1/ubuntu/xenial/thirdparty

There was missing /stable/ part was missing in 3rdparty library paths.

Fix wrong urls in Dovecot Pro release 2.3.9.2-rev1 3rdparty repository documentation

---

source/configuration_manual/fts/index.rst

mysql doesn't support async operations.

fts: Don't use dict-async socket in mysql example

---

source/configuration_manual/stats/index.rst

Cleanup from https://github.com/dovecot/documentation/pull/11 that's unrelated to histogram support.

configuration_manual/stats: Fix formatting

---

source/configuration_manual/stats/index.rst

Based on the changes in the closed https://github.com/dovecot/documentation/pull/11 PR.  This documents the discrete group_by functionality that's already in core.

configuration_manual/stats: Document group_by

---

source/conf.py

Lets try to help people find that this documentation exists in github and they can send pull requests. I was trying to add it also to the footer but that failed.

Add "Edit Documentation" navigation link

---

source/configuration_manual/stats/index.rst

We renamed these from 'name' to 'cmd_name' back in ~November but it looks like these examples sneaked in/past us.

configuration manual: Fix imap_command_finished's command name field name

---

source/configuration_manual/stats/index.rst

But it wasn't obvious from the docs. Now it is.

group_by was only added in 2.3.10

---

source/settings/plugin/advanced/obox.rst

As the usage of this setting is not recommended anyways, don't mark it
as deprecated but remove it right away.
DOV-3842

settings/plugin/advanced/obox: Remove obox_mailbox_list_quick_lookups

---

source/configuration_manual/authentication/password_schemes.rst

@cmouse I'm not sure where this "$1$" prefix came from?

configuration_manual/authentication: Add details about PBKDF2 encoding

---

source/configuration_manual/event_filter.rst
source/configuration_manual/stats/index.rst
source/configuration_manual/stats/openmetrics.rst
source/settings/core.rst

This documents what happens right now in released versions of dovecot.  It also adds a warning that event filtering will change in the near future, but it does not contain the docs for the new language.  That'll be a separate PR.

Document current event filtering

---

source/configuration_manual/authentication/auth_policy.rst

Remove the example setting so nobody will try to use it.

auth_policy: Clarify auth_policy_hash_nonce setting

---

source/configuration_manual/authentication/proxies.rst
source/configuration_manual/config_file/time.rst
source/configuration_manual/mail_location/obox/http_storages.rst
source/settings/core.rst
source/settings/plugin/advanced/obox.rst
source/settings/plugin/obox-plugin.rst

Jira: DOV-4028
Also fixes several settings to use time_msecs type rather than just time.

Add missing obox/fs-auth settings

---

source/configuration_manual/authentication/oauth2.rst
source/settings/plugin/acl.rst

I did my best to expand the ACL documentation to make a story of sharing mailboxes somehow smoother for people who are new to dovecot like me.
- Made it clear that the per-user and global ACLs serve different purposes, and aren't different implementation of the same.
- Added an interpretation to the global ACL example.
- Connected ACL documentation to the dictionaries documentation, which was only present as hints in config files or external tutorials.
based on the thread https://dovecot.org/pipermail/dovecot/2020-September/119925.html Thanks to Daniel Miller!

Added details to the ACL documentation.

---

source/configuration_manual/authentication/user_databases_userdb.rst

Fixed typo, also changed - to No for clarity.

Fix typo in userdb documentation (Passdb -> Userdb) and - to No.

---

source/admin_manual/director/index.rst
source/admin_manual/director/rebalancing_backends.rst

It's a bit confusing since the director servers themselves aren't being rebalanced.

admin_manual: Rename "rebalancing directors" to "rebalancing backends"

---

source/configuration_manual/stats/index.rst
source/configuration_manual/stats/openmetrics.rst

- Conventions used in OpenMetrics exposition
- Upper case for commands used in auto-generated grouped metrics in stats

Update Metrics documentation

---

source/settings/plugin/fts-plugin.rst

settings/fts: Add missing escape to special-use \Trash

---

source/installation_guide/upgrading/from-2.3-to-2.3.12.rst
source/installation_guide/upgrading/from-2.3-to-2.3.x.rst
source/installation_guide/upgrading/from-2.3-to-2.4.rst
source/installation_guide/upgrading/index.rst

Also break-imap-search was removed in v2.3.7, not v2.4.

upgrading: Merge v2.3.x upgrades into one page

---

source/configuration_manual/mail_location/obox/http_storages.rst

In the parameters table loghdr's ``versionadded`` is not rendered correctly https://doc.dovecot.org/configuration_manual/mail_location/obox/http_storages/index.html

configuration_manual: http_storages: Fix wrongly rendered versionadded

---

source/admin_manual/list_of_events.rst
source/installation_guide/upgrading/from-2.3-to-2.3.x.rst

Change is important, but a bit technically complicated, so publicly
document why it was done.
DOV-3954

Upgrade: Add thorough exaplanation of max_bucket ID shrinking

---

source/configuration_manual/authentication/oauth2.rst

- base64-decoded JWT example was absent in the rendered document due to a missing space
- Validation key paths were not rendered as code blocks, instead the `::` formatters were rendered
- The lists of supported features and key algorithms were wrongly indented, being rendered as a quote (GitHub flavor only, not in on doc.dovecot.org)

Fix "Local Validation" section of OAuth2 authentication

---

source/configuration_manual/howto/antispam_with_sieve.rst

This removes the `-C report` option from the `spamc` scripts in the documentation.
According to the spamc man page, `-L` and `-C` are mutually-exclusive, and attempting to use both together will result in the error message "Learning excludes reporting to collaborative filtering databases"

Don't use mutually-exclusive options in spamc script

---

source/admin_manual/lua.rst

Global variables are disallowed.

admin_manual: lua: Document environment change in 2.3.17

---

source/configuration_manual/mail_location/obox/dictmap_cassandra.rst

debug_queries and latency_aware_routing settings are yes if the key
exists; value portion is ignored
DOP-480

dictmap_cassandra: Fix boolean setting examples

---

source/configuration_manual/config_file/config_variables.rst
source/settings/core.rst

This PR includes several related clarifications:
- Reword `client_id` authentication variable,
- reword `imap_id_retain` settings variable, and
- add relevant links between `imap_id_retain`, `imap_id_log` (from settings/core) and `client_id` auth varibale (from config_file/config_variable).
DOV-4940

Clarify `client_id` authentication variables

---

source/configuration_manual/namespace/index.rst

Conform to current documentation standards
Remove duplicate setting information
Move mailbox settings into a form you can actually read and understand :)

Rewrite namespace page

---

source/_ext/dovecot_sphinx.py
source/_static/custom.css
source/settings/core.rst

@sirainen : This hopefully addresses your comment about UI separation elements between settings from #344.

Directive settings cleanup

---

.github/workflows/main.yml

For [reasons](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability), you can't use `secrets` in `if`, but you can put a secret into an `env` and then use `env` in the `if`.

Guard against forks without deploy keys

---

source/_ext/dovecot_sphinx.py
source/configuration_manual/authentication/user_database_extra_fields.rst
source/configuration_manual/replication.rst
source/configuration_manual/sieve/plugins/extprograms.rst
source/configuration_manual/sieve/plugins/imapsieve.rst
source/configuration_manual/sieve/usage.rst
source/installation_guide/upgrading/from-1.0-to-1.1.rst
source/settings/core.rst
source/settings/pigeonhole-ext/imapsieve.rst

Non-existent reference, e.g. ":dovecot_core:ref:`foobar`", now gives:
Warning, treated as error:
/home/slusarz/dovecot/documentation/source/admin_manual/logging.rst:9:Missing cross-reference: 'foobar'
make: *** [Makefile:19: html] Error 2

settings: Error if setting xref doesn't exist

---

source/admin_manual/system_users_used_by_dovecot.rst
source/configuration_manual/authentication/master_users.rst
source/configuration_manual/authentication/password_databases_passdb.rst
source/configuration_manual/authentication/password_schemes.rst
source/configuration_manual/authentication/shadow.rst
source/configuration_manual/authentication/user_databases_userdb.rst

- Mark shadow passdb driver as deprecated, and
- remove unnecessary references to removed auth driver.

configuration_manual/authentication: Remove shadow passdb driver

---

source/configuration_manual/fts/index.rst
source/configuration_manual/fts/lucene.rst

note: there is also a reference to the package dovecot-lucene in debian-packages.rst and ubuntu-packages.rst,
but I didn't remove it as I guess that should happen when the release system removes it as well ?
there were also other references, in solr.rst and fts-plugin.rst, but for what I understand they mention lucene used in solr, not fts-lucene itself.

fts-lucene: Removing the plugin

---

.github/actions/spelling/expect.txt
source/configuration_manual/mail_location/index.rst

- Move `DIRNAME` back to main keys table,
- change `DIRNAME` deprecation version, and
- communicate bug when renaming folders using `FULLDIRNAME` together
with certain other options.

configuration_manual/mail_location: Update DIRNAME/FULLDIRNAME keys

---

source/admin_manual/lua.rst

Broken in 55e20b7ec58a9be4bccc0931c9af2f5d066def5e

admin_manual/lua: Fix rst syntax

---

source/admin_manual/error_codes.rst
source/configuration_manual/config_file/config_variables.rst
source/developer_manual/design/mailbox_list.rst
source/installation_guide/upgrading/from-2.3-to-3.0.rst

Update the documentation to remove direct references to the `dsync` command (or symlink to `doveadm`).
Most other remaining references are mainly due to:
- Describing the design/operation/general idea behind the `doveadm sync` operation (aptly named `dsync`), or
- old update guides that explicitly state `dsync` because that still existed.
Closes DOV-5011

Dov 5011/remove dsync command

---

source/admin_manual/lua.rst

Broken in 55e20b7ec58a9be4bccc0931c9af2f5d066def5e

2.3 CHERRY-PICK: admin_manual/lua: Fix rst syntax

---

.github/actions/spelling/expect.txt
source/admin_manual/chrooting.rst
source/admin_manual/errors/chgrp_no_perm.rst
source/admin_manual/errors/index.rst
source/admin_manual/errors/socket_unavailable.rst
source/admin_manual/errors/time_moved_backwards.rst
source/configuration_manual/authentication/digest-md5.rst
source/configuration_manual/authentication/winbind.rst
source/installation_guide/dovecot_community_repositories/compiling_source.rst

This PR imports missing pages from the obsolete wiki, that are still referenced in the dovecot core project.
These pages were imported/converted from the wiki and afterwards manually updated, so that the links and contained information are up-to-date (as best as I could).
Closes DOV-5043

DOV-5043: Remove references to obsolete wiki

---

source/configuration_manual/mail_location/obox/amazon_s3.rst
source/configuration_manual/mail_location/obox/dictmap.rst
source/configuration_manual/mail_location/obox/s3.rst
source/configuration_manual/mail_location/obox/scality_cdmi.rst
source/configuration_manual/plugins/fs-compress-plugin.rst
source/configuration_manual/zlib_plugin.rst
source/settings/plugin/zlib-plugin.rst

Replace `gz` with `zstd` in compression algorithm documentation:
- Main examples of `zlib_save`/`zlib_save_level`, and
- fs-compress example usages.
Closes DOV-5009

DOV-5009 - update compression documentation

---

.github/actions/spelling/expect.txt
source/admin_manual/mailbox_formats.rst
source/admin_manual/mailbox_formats/dbox.rst
source/admin_manual/mailbox_formats/maildir.rst
source/admin_manual/mailbox_formats/pop3c.rst
source/configuration_manual/fts/dovecot.rst
source/configuration_manual/fts/index.rst
source/configuration_manual/mail_location/obox/dictmap.rst
source/configuration_manual/mail_location/obox/index.rst
source/configuration_manual/quota/unified_quota_configuration.rst
source/installation_guide/dovecot_pro_releases/index.rst
source/installation_guide/dovecot_pro_releases/repository_guide.rst
source/settings/plugin/fts-dovecot-plugin.rst
source/settings/plugin/fts-plugin.rst
source/settings/plugin/pop3-uidl-migrate-plugin.rst
source/settings/plugin/vault-plugin.rst

This PR specifies which mailbox format is supported by Dovecot Pro. Once for each individual page, as well as in the main overview table.
I also took the liberty to remove stray whitespaces in files I touched anyways.
Closes DOV-4458

Dov-4458: Clarify supported mailbox formats

---

.github/actions/spelling/expect.txt
source/configuration_manual/authentication/checkpassword.rst

Also change the Lua reference into a note. It was confusing earlier, especially it looked like checkpassword was new in
v2.3.0 rather than Lua being new in v2.3.0.

2.3 ONLY: checkpassword: Add missing documentation

---

source/settings/plugin/mailbox-alias-plugin.rst

When merged, change https://wiki.dovecot.org/Plugins/MailboxAlias to point to https://doc.dovecot.org/settings/plugin/mailbox-alias-plugin/

mailbox-alias-plugin: Copy documentation from wiki

---

source/configuration_manual/acl.rst
source/installation_guide/upgrading/from-2.3-to-3.0.rst

This PR adds a clarification section regarding migrating ACL directories to appropriate files, as the former has been deprecated and is going to be deleted starting with v3.0 going forward.
Closes DOV-5266

DOV-5266 - Document migration from Global ACL Directories to Files

---

source/configuration_manual/sieve/extensions/duplicate.rst

There's a typo in the number of the RFC: it has to be 7352 (Sieve Email Filtering: Detecting Duplicate Deliveries) instead of 7353 (Security Requirements for BGP Path Validation). But the link to the IETF website is/was correct.

Typo in number of RFC

---

.github/actions/spelling/expect.txt
source/installation_guide/dovecot_community_repositories/compiling_source.rst
source/installation_guide/dovecot_community_repositories/source_tarballs.rst
source/installation_guide/index.rst

Changes:
- Document decision/clarification about target platform, compiler and c standard,
- add link from source_tarballs to compile_sources, and
- remove requirement of pandoc in compile_sources.

DOV-5284: Streamline compilation effort

---

source/installation_guide/dovecot_community_repositories/source_tarballs.rst
source/installation_guide/index.rst

- Fix internal link incorrectly pasted from anchor label (i.e. erroneously prefixed with `_`), and
- fix external link incorrectly prefixed with `:ref:`.
Closes DOV-5437.

DOV-5437: Fix compilation links

---

.github/workflows/spelling.yml

Missed this in:
a6560986d63d0eba36b8a99417de5c8f720858d1

check-spelling should use same version throughout

---

source/configuration_manual/namespace/index.rst

configuration_manual/namespace: Fix typo

---

.github/actions/spelling/expect.txt
source/configuration_manual/push_notification.rst

Add description of Chronos push notification backend. The description and layout is mostly copied from the OX backend with amendments to accomodate for the new backend.
Closes DOV-5487.

DOV-5487: Add description for chronos push notification backend

---

source/configuration_manual/namespace/index.rst

DOV-5602: Document warning for non-standard special-use flags

---

source/configuration_manual/push_notification.rst

For the sake of consistency the push notification plugin for the Chronos driver is to be made consistent with the other existing plugins (i.e. the lua push notification plugin in particular). This is done now, as no widespread distribution can be assumed.
This PR also includes a previous documentation PR, that updated the configuration description to be more consistent with the lua one. Specifically in terms of how to enable the plugin.
Closes DOV-5655.

DOV-5655: Rename `chronos` push notification plugin

---

source/configuration_manual/event_filter.rst

DOV-5562: Document size comparisons using units in configuration_manual/event_filter

---

source/configuration_manual/push_notification.rst

Increase default `msg_max_size` for chronos push notification plugin

---

.github/actions/spelling/expect.txt
source/configuration_manual/sieve/plugins/extprograms.rst

Fix incorrect spelling of word "uncomment" in sieve plugin's extprogram page and remove it from the spelling file.

Fix spelling of word "uncomment"

---

source/configuration_manual/config_file/config_variables.rst

This exists only in v2.4/v3.0.

config_variables: Remove base64url from hash formats

---

source/configuration_manual/event_filter.rst

DOV-5726: Document type mismatch/unsupported operations warnings in event filters

---

source/configuration_manual/authentication/gssapi.rst

The indentation is correct for the command output, but sphinx has issues with it, so remove the extra indent to make it happy.
Broken in 1ad72462b8f0e57226ae6bf402fe7ef2bb2653af

authentication/gssapi: Fix indentation

---

source/configuration_manual/fts/dovecot.rst

This works only in the 3.0 branch.

fts-dovecot: Remove :man: reference

---

source/_ext/dovecot_sphinx.py
source/admin_manual/list_of_events.rst
source/configuration_manual/config_file/config_variables.rst
source/installation_guide/upgrading/from-2.3-to-3.0.rst
source/settings/core.rst

Add the `imap_id_param` event description with its respective fields. Also deprecate references to the `imap_id_log` setting which is replaced by the new event.
Also fix some issues that cropped up on the event-page:
- Fix the manual class assignments that were used for styling the expand/collapse buttons and their respective functionality.
- Fix the `pop3_client` event that was incorrectly converted to a field_group before.
- Fix `local_part`/`remote_part` typo: `part` -> `port`.
- Drop the unnecessary and distracting animation-attribute of the sphinx-dropdowns.
Closes DOV-5738.

DOV-5738: Document `imap_id_param` event

---

source/_ext/dovecot_sphinx.py
source/admin_manual/event_design.rst
source/admin_manual/list_of_events.rst
source/configuration_manual/config_file/config_variables.rst
source/configuration_manual/event_export.rst
source/configuration_manual/event_filter.rst
source/configuration_manual/service_configuration.rst
source/configuration_manual/sieve/examples.rst
source/configuration_manual/stats/index.rst
source/configuration_manual/stats/openmetrics.rst
source/installation_guide/upgrading/from-2.3-to-3.0.rst
source/settings/core.rst
source/settings/pigeonhole.rst

Remove the following deprecated parts:
- Mark deprecated sieve storage settings 'sieve_dir', 'sieve_global_path', and 'sieve_global_dir' as removed,
- update sieve include extension examples with the current sieve storage settings.
Closes DOV-5585.

DOV-5585: Remove sieve storage deprecations

---

source/_ext/dovecot_sphinx.py

There may be multiple child nodes we need to process, so return all of them from _parse_rst() instead of just the first
Sphinx DOM/docutils is a mess to understand, but this seems to work.
DOV-6075

dovecot_sphinx: Fix parse_rst behavior

---

source/configuration_manual/protocols/imap.rst

This page, or all the protocols pages in general, could use some rewriting.

protocols/imap: Remove completely wrong duplicated content

---

source/pigeonhole-man/doveadm-sieve.1.rst.in

This is the bootsrap command that gets scriptnames; you don't need to pass one in.
Also, indicate that this command returns both the script name and the active status.

pigeonhole-man: Remove scriptname argument

---

source/configuration_manual/authentication/static_user_database.rst

In this page the PAM link seems out of place:
https://doc.dovecot.org/configuration_manual/authentication/static_user_database/
I moved the link to the place where the PAM term is mentioned but I am not 100% sure so check with that in mind.

Update PAM reference in static_user_database.rst

---

source/man/dovecot-lda.1.rst.in

This means the user is not known.

man: dovecot-lda - Document exit code 67

---

source/configuration_manual/push_notification.rst
source/settings/plugin/push-notification-plugin.rst

Rewrite the documentation of the currently implemented push notification plugins.
Note: There are http-client settings that can be used in the plugins, that are currently not documented, yet. This will be done in another PR.

DOV-6118: Config-Rewrite of the Push Notification Plugin

---

.github/workflows/spectral.yml

When I upgraded my fork, I got failures from this workflow: https://github.com/check-spelling-sandbox/dovecot-documentation/actions/workflows/spectral.yml
This adds a look-before-you-leap check which saves ~30s of useless cpu cycles for my org but would still allow me to use the workflow if I configured the secret.

Only run spectral when it could work

---

source/configuration_manual/config_file/index.rst
source/configuration_manual/fs/index.rst
source/configuration_manual/fts/dovecot.rst
source/configuration_manual/mail_crypt_plugin.rst
source/configuration_manual/mail_location/obox/amazon_s3.rst
source/configuration_manual/mail_location/obox/dictmap.rst
source/configuration_manual/mail_location/obox/fscache.rst
source/configuration_manual/mail_location/obox/s3.rst
source/configuration_manual/mail_location/obox/scality_cdmi.rst
source/configuration_manual/mail_location/obox/scality_sproxyd.rst
source/configuration_manual/namespace/index.rst
source/configuration_manual/plugins/fs-compress-plugin.rst
source/man/doveadm-dict.1.rst.in
source/man/doveadm-fs.1.rst.in
source/settings/core.rst
source/settings/plugin/fts-dovecot-plugin.rst
source/settings/plugin/obox-plugin.rst

Jira: DOV-6316
On top of https://github.com/dovecot/documentation/pull/826

settings redesign: Redesign fs_parent

---

source/admin_manual/debugging/debugging_rawlog.rst
source/configuration_manual/config_file/config_variables.rst
source/configuration_manual/general_backend_settings.rst
source/configuration_manual/resource_usage.rst
source/configuration_manual/system_calls_optimization.rst
source/developer_manual/development_tips/valgrind.rst
source/settings/core.rst

- Add new distribution attributes, accessible via `%{dovecot:<key>}` syntax,
- add `os` as well as `os-release` variables to `system:` key,
- document changes of `imap_id_send` rewrite as strlist, and
- document changes of `import_environment` rewrite as strlist.

DOV-6305: Rewrite `import_environment` and `imap_id_send` as strlist

---

source/admin_manual/lua.rst

When sending payload, it no longer expects 100 Continue header unless asked to.
JIRA: DOV-6369

admin_manual: lua - Document changes to set_payload()

---

source/configuration_manual/authentication/authentication_via_remote_imap_server.rst
source/configuration_manual/authentication/password_databases_passdb.rst
source/configuration_manual/config_file/config_variables.rst
source/configuration_manual/mail_location/imapc/index.rst
source/configuration_manual/shared_mailboxes/cluster_setup.rst
source/configuration_manual/shared_mailboxes/cluster_setup_example.rst

- Document `%{owner_user}` %variable,
- update default value of `imapc_user`,
- update default value of `imapc_max_line_length`, 
- add `imapc_connection_timeout_interval` setting,
- mark `imapc_ssl_verify` as removed, and
- update IMAP Password Database description with links to the proper settings and updated example.
Closes DOV-6456.

DOV-6456: Update IMAP Password Database

---

.vitepress/config.js

sidebar plugin had an API change that was ignoring exclude directive in frontmatter for placeholder files.

vitepress: Fix 404's in sidebar

---

source/configuration_manual/imap_metadata.rst

Document how to use SQL and Redis for storing IMAP metadata.
Thanks for Joseph D Wagner for testing the SQL part.

imap_metadata: Document how to use non-file based storage

---

data/settings.js

This was removed in March 2023:
lib-master: Remove unused config_cache_size setting

settings: Remove config_cache_size

---

.github/workflows/ci.yml
lib/link_checker.js
lib/utility.js
package.json

It is too unstable at the moment. Not sure if it is a library limitation or something else.
Move this checking to an explicit 'npm run docs:build-checks' command.
Thus, both CI and deployment builds will ignore (for now).

vitepress: Disable default link checking on build

---

.vitepress/config.js

This removes an ~30KB chunk of code from all ~300 individual pages, and moves to a centralized, cacheable javascript file.
See: https://vitepress.dev/reference/site-config#metachunk

vitepress: enable metaChunk setting

---

components/SettingsComponent.vue
docs/core/summaries/settings.md

* Don't hide in details box on summary page, as the right-side links won't work correctly
* Show advanced settings on topic pages (i.e. plugin settings) to accurately document all levers available
* Add a red-box to the detail information if this is an advanced setting, to make clear it should not normally be changed.

Improved display of advanced settings

---

docs/core/man/include/doveadm-backup-sync.inc
docs/core/man/include/doveadm-copy-move.inc
docs/core/man/include/global-options-formatter.inc
util/generate_man.js

This was breaking rendering in VitePress, as the include paths are relative to the file, not the page rendering the include file
Need to fix man generation utility, with this change, by passing in the filepath of the included file in recursive calls, rather than the original file.

man: Fix include paths in include files

---

package-lock.json

micromatch is a dependency of fast-glob, which isn't bundled into browser JS, so this is only a local security issue when building/testing

npm: bump dependency due to security alert

---

docs/core/config/sieve/submission.md

%L is not valid value at all. Probably %Ln was intended.

config/sieve/submission: Fix auth_username_format note

---

data/settings.js
docs/core/config/auth/caching.md
docs/core/config/dict.md
docs/core/config/imap.md
docs/core/config/shared_mailboxes.md
docs/core/man/doveadm-altmove.1.md
docs/core/man/doveadm-quota.1.md
docs/core/man/dovecot.1.md
docs/core/plugins/last_login.md
docs/core/plugins/lazy_expunge.md
docs/core/plugins/notify_status.md
docs/core/plugins/sieve.md
docs/core/settings/types.md
docs/howto/convert_password_schemes.md

config-rewrite: Lots of fixes

---

README.md
lib/markdown.js

GitHub Issue #1017
The code silently was supporting a 2nd argument, that would have been added as an anchor to the URL. However, that kind of linking has been replaced by dovecotlinks functionality.  Additionally, there were already several existing plugin links that was already using the 2nd argument as a "text" replacement, so just change to that usage.

markdown: Add ability to change text for a Dovecot plugin link

---

README.md
docs/core/admin/guides/spam_reporting.md
docs/core/config/auth/userdb.md
docs/installation/upgrade/include/2.3-to-2.3.x.inc
lib/markdown.js

Setting set link text

---

lib/utility.js
package-lock.json
package.json

API breaking, so requires code changes

npm: Upgrade path-to-regexp to fix high severity vulnerability

---

data/settings.js
data/updates.js
docs/core/config/auth/databases/oauth2.md
docs/core/config/auth/mechanisms/kerberos.md

config-rewrite: auth: Rename passdb_mechanisms to passdb_mechanisms_filter 

---

data/settings.js
docs/core/config/service.md

config-rewrite: Rename service_idle_kill to service_idle_kill_interval

---

data/updates.js
docs/core/config/auth/passdb.md

auth/passdb: Document nologin behavior with lmtp and doveadm

---

source/admin_manual/director/backend_modifications.rst

Backend modifications guide mixed the words director/backend in two places.

backend_modifications: improved clarity

---

docs/core/plugins/mail_crypt.md
docs/core/settings/types.md

settings, global: Replace FILE setting type syntax

---

data/doveadm.js
docs/core/man/doveadm.1.md

Update doveadm [mail] fs commands

---

util/generate_man.js

Refactor generate_man

---

.vitepress/config.js
lib/data/doveadm.data.js
lib/data/event_categories.data.js
lib/data/event_reasons.data.js
lib/data/events.data.js
lib/data/lua.data.js
lib/data/settings.data.js
lib/markdown.js
lib/utility.js
package-lock.json
package.json

We always want loadData() to be a blocking call, as we use that code to read the data JS files so that we can do further processing.
However, since data JS paths are dynamic, we must use import() which is required to be an async call.
For bootstrapping purposes, this means there is no way to block markdown processing to begin before the Dovecot markdown plugin is ready. This is because markdown-it code MUST NOT use async code, so we need to load all the data (via loadData()) before it can be initialized. Dovecot markdown code also requires VitePress paths to be available in global config object, so the only place we can realistically add the Dovecot markdown processing is via the "config" markdown option. Unfortunately, the internal VitePress code does not call this function with await, …

utility.js: Make loadData() a sync function

---

docs/core/config/dict.md

config/dict: Add max_idle_time for dict-ldap

---

docs/core/settings/types.md
docs/core/settings/variables.md

settings: Fix/clarify %variable escaping

---

.github/actions/spelling/patterns.txt
docs/core/man/doveconf.1.md

doveconf: Add filter parameter

---

docs/core/config/shared_mailboxes.md
docs/core/plugins/quota_clone.md
docs/core/recommended_metrics.md
docs/core/recommended_metrics_include/backend.inc
docs/core/recommended_metrics_include/header.inc
docs/core/recommended_metrics_include/proxy.inc

Use dict_maps directly in configs

---

data/settings.js

data/settings: Update mail_prefetch_count description

---

docs/core/admin/login_proxy.md
docs/core/config/submission.md

submission: Add additional high-level design information from Stephan

---

components/LuaFunctionComponent.vue
data/lua.js
data/settings.js
lib/data/lua.data.js

They are now parsed via settings parser, which does not have msecs suffix.
JIRA: DOV-6912

data/lua: Drop _msecs from http client settings

---

data/settings.js
docs/core/config/auth/policy.md
docs/core/settings/types.md

config-rewrite: auth_policy_request_attributes should be strlist

---

.github/actions/spelling/expect.txt
docs/core/design/var_expand.md
docs/core/plugins/mail_crypt.md
docs/installation/upgrade/2.3-to-2.4.md
docs/installation/upgrade/include/2.4-var-expand.inc

upgrade: Variable expansion

---

docs/core/config/guides/quick.md

Reorder the settings to make more sense. Update comments. Remove the lower-filter from %{user}, because the default auth_username_format already lowercases the user.

guides/quick: Minor tweaks to quick configuration example

---

data/settings.js
docs/core/config/shared_mailboxes.md

Fixes to %%variables

---

docs/core/plugins/quota.md

quota: Clarify that quota service doesn't work in a cluster

---

data/settings.js
docs/core/config/auth/databases/ldap.md
docs/core/config/auth/databases/passwd.md
docs/core/config/auth/databases/passwd_file.md
docs/core/settings/variables.md

Convert missing variables

---

data/settings.js
docs/installation/upgrade/include/2.4-converted-settings.inc

settings: Rename fts_index_timeout to fts_search_timeout

---

data/settings.js
docs/installation/upgrade/include/2.4-default-settings.inc

settings: Protocols is empty by default

---

docs/core/admin/guides/rootless.md
docs/core/config/guides/quick.md
docs/core/config/service.md

Remove references to previous example configuration

---

data/settings.js
docs/core/config/auth/databases/ldap.md
docs/core/config/auth/databases/pam.md
docs/core/config/auth/master_users.md
docs/core/config/auth/proxies.md
docs/core/config/auth/userdb.md
docs/core/config/pop3.md
docs/core/config/shared_mailboxes.md
docs/core/config/statistics.md
docs/core/config/users/virtual.md
docs/core/design/auth_process.md
docs/core/design/mail_user.md
docs/core/man/include/option-A.inc
docs/core/plugins/fts.md
docs/core/plugins/lazy_expunge.md
docs/core/plugins/push_notification_lua.md
docs/core/plugins/quota.md
docs/core/plugins/virtual.md
docs/core/settings/types.md
docs/howto/convert_password_schemes.md
docs/howto/imapc_proxy.md
docs/howto/lmtp/exim.md
docs/howto/restrict_access.md
docs/howto/virtual/simple_install.md

DOV-7293
On top of https://github.com/dovecot/documentation/pull/1102

Config rewrite fixups

---

docs/core/settings/variables.md

settings: variables - Document local and remote port

---

data/settings.js
docs/core/config/guides/quick.md
docs/core/config/service.md
docs/core/config/ssl.md
docs/core/man/doveconf.1.md
docs/core/man/dovecot.1.md
docs/howto/imapc_proxy.md
docs/howto/virtual/postfix.md
docs/installation/upgrade/include/2.4-removed-other-features.inc

DOV-7302
On top of https://github.com/dovecot/documentation/pull/1106

global: Add ssl_server_ prefix to ssl server settings

---

components/DoveadmCliComponent.vue
components/DoveadmComponent.vue
components/DoveadmHttpApiComponent.vue
data/doveadm.js
lib/data/doveadm.data.js
lib/doveadm.js
package-lock.json
package.json

DOV-7017
Still have to do all the hardwork of adding the various examples and response data to doveadm.js... But don't want to wait for that since it's not necessary for adding this base functionality.
(FYI: I already have done some work on the examples data, so maybe I'll throw that in a WIP MR for now.)

Improve doveadm documentation

---

docs/core/settings/syntax.md
docs/core/settings/types.md

settings/syntax: Describe effect of %variables better

---

.github/actions/spelling/expect.txt
docs/core/design/dcrypt.md

- Cleanup page,
- amend file format 2 description and
- add exhausting documentation for the new `dcrypt-decrypt.py` script. (Which depending on review might not yet be fully published.)
Closes DOV-7024.

DOV-7024: Improve dcrypt design documentation

---

docs/core/settings/syntax.md

Add necessary reference to allow linking into the release notes.
Closes DOV-6869.

DOV-6869: Link release notes for 3.1

---

package.json

This is needed for some npm-like tools (e.g. bun) for some actions

npm: Add name to package.json

---

components/DoveadmComponent.vue
components/DoveadmHttpApiComponent.vue
data/doveadm.js
docs/core/admin/doveadm.md
lib/data/doveadm.data.js
lib/doveadm.js

Doveadm responses are so variable, that creating an abstract system for documenting would be extremely difficult.
To simplify (for now), do the following:
- Only worry about HTTP API responses
- Allow for free-form description of response info
- Allow for markdown enabled description of the response

doveadm: Simplify doveadm response display

---

data/settings.js
docs/core/config/auth/databases/oauth2.md

The oauth2_ prefix wasn't originally needed when it was under oauth2 {} but that ended up causing issues elsewhere, so now it's needed.

global: Rename local_validation to oauth2_local_validation

---

docs/core/man/doveconf.1.md

- Remove the unsupported `-f` parameter,
- rewrite description to fix formatting issues.
Closes DOV-7357.

DOV-7357: Fix doveconf manpage

---

docs/howto/sasl/exim.md
docs/installation/upgrade/2.3-to-2.4.md
docs/installation/upgrade/include/2.4-exim.inc

 howto/exim, upgrade: Use auth-legacy socket type for Exim authentication 

---

.github/actions/spelling/patterns.txt
docs/core/man/doveconf.1.md

man/doveconf: Add -U parameter

---

data/settings.js
data/updates.js
docs/installation/upgrade/2.4-to-2.4.x.md

- Update default value,
- describe how to reset the previous behavior.

DOV-7527: Change the default lmtp_user_concurrency_limit to 10

---

docs/core/plugins/quota.md
docs/howto/virtual/postfix.md

Otherwise it can't be easily overridden by userdb.

quota, howto: Specify quota_storage_size outside quota root in examples

---

docs/core/config/namespaces.md

config/namespace: Fix mail_index_path for mixed mbox/maildir example

---

data/settings.js
docs/core/config/auth/passdb.md
docs/core/settings/variables.md

Document peer certificate fingerprinting

---

data/settings.js

Remove passdb and userdb_args

---

docs/core/config/namespaces.md

Add info about suggested @mailbox_defaults setting

core/docs/core/config/namespaces.md: Add @mailbox_defaults

---

data/settings.js
data/updates.js

login_proxy_rawlog_dir: Indicate login variable support

---

.github/workflows/2_3.yml
.github/workflows/main.yml

2.3 release would build all of vitepress documentation even though it is never used.
Regardless, given EOL of 2.3, it should be removed from the "main" release action anyway.

github: Separate 2.3 and 2.4 release workflows
